[package]
name = "token"
version = "1.0.0"

[addresses]
token = "_"
deployer = "_"

[dev-addresses]
token = "0xc3bb8488ab1a5815a9d543d7e41b0e0df46a7396f89b22821f07a4362f75ddc5"
deployer = "0xcafe"

[dependencies]
AptosFramework = { local = "./framework/aptos-framework" }
